## Single Dimension NumPy Array

In [2]:
!pip install numpy

In [4]:
import numpy as np
n1 = np.array([10,20,30,40,50,60,70,80,90,100])
n1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [6]:
print(n1)

[ 10  20  30  40  50  60  70  80  90 100]


In [10]:
type(n1)

numpy.ndarray

## Multidimensional NumPy Array

In [15]:
import numpy as np
n2 = np.array([[10,20,30],
               [40,50,60],
               [70,80,90]])
n2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## Initialize NumPy array with zeros

In [18]:
n3=np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

## Initialization array of matrix with full then

In [23]:
n4 = np.full((3,3),9)

In [25]:
n4

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

## Initialization of NumPy array within a range

In [30]:
n5 = np.arange(10,20)

In [32]:
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Initilization of the NumPy array with the skip numbers

In [35]:
n6 = np.arange(1,10,2)


In [37]:
n6

array([1, 3, 5, 7, 9])

## Initilization NumPy array with the random numbers

In [40]:
n7 = np.random.randint(100,1000,10)

In [42]:
n7

array([915, 684, 709, 949, 153, 957, 103, 853, 684, 682])

## Initialization the array shape changes in a fraction of shape

In [47]:
n8 = np.array([[10,20,30],[10,30,40],[20,60,80],[10,30,40]])
n8

array([[10, 20, 30],
       [10, 30, 40],
       [20, 60, 80],
       [10, 30, 40]])

In [49]:
n8.shape

(4, 3)

In [53]:
n8.shape=(3,4)

In [56]:
n8

array([[10, 20, 30, 10],
       [30, 40, 20, 60],
       [80, 10, 30, 40]])

## Joining NumPy array

In [61]:
import numpy as np

In [63]:
a = np.array([10,20,30])
b = np.array([20,30,40])

In [73]:
np.vstack((a,b)) #joining the numpy as vertical stacking

array([[10, 20, 30],
       [20, 30, 40]])

In [75]:
np.hstack((a,b)) #joining the numpy as horizontal stacking

array([10, 20, 30, 20, 30, 40])

In [77]:
np.column_stack((a,b)) #joining the numpy as column stacking

array([[10, 20],
       [20, 30],
       [30, 40]])

In [79]:
np.hstack((b,a))

array([20, 30, 40, 10, 20, 30])

## NumPy intersection and difference

In [82]:
x=np.array([10,20,30,40,50,60])

In [84]:
y=np.array([30,50,90,100,120,150])

In [86]:
np.intersect1d(x,y)

array([30, 50])

In [90]:
np.setdiff1d(x,y)

array([10, 20, 40, 60])

## Addition of NumPy Arrays

In [93]:
t = np.array([10,20])
s = np.array([30,40])

In [95]:
np.sum([t,s])

100

In [97]:
np.sum([t,s],axis=0)

array([40, 60])

In [99]:
np.sum([t,s],axis=1)

array([30, 70])

## NumPy array mathematics

In [102]:
p = np.array([10,20,30])

In [104]:
p+1

array([11, 21, 31])

In [106]:
p/2

array([ 5., 10., 15.])

In [108]:
p*2

array([20, 40, 60])

In [110]:
p-2

array([ 8, 18, 28])

In [112]:
p**2

array([100, 400, 900])

## NumPy maths functions

In [117]:
nn = np.array([10,20,30,60])

In [119]:
np.mean(nn)

30.0

In [121]:
np.std(nn)

18.708286933869708

In [123]:
np.median(nn)

25.0

## Saving and loading NumPy array

In [128]:
n11 = np.array([10,20,30,40,50])

In [134]:
np.save('my_name',n11) #saving the numpy array

In [136]:
np.load('my_name.npy') #loading the NumPy array

array([10, 20, 30, 40, 50])

## Uniform 


In [149]:
np.random.uniform(5,10, size = 4)

array([6.47909113, 8.56919192, 6.10958017, 6.76476639])

In [151]:
np.random.uniform(size = 5)

array([0.11947221, 0.74452084, 0.05013402, 0.34333559, 0.1575075 ])

In [153]:
np.random.uniform(size = (2,3))

array([[0.1842393 , 0.30959667, 0.65148873],
       [0.69990549, 0.20819439, 0.20527926]])

In [155]:
np.random.uniform(10,100,size = (2,3))


array([[50.71679268, 11.94905331, 38.08634494],
       [45.98792116, 83.53593645, 39.87575333]])

## Logspace

In [159]:
np.logspace(0,10,5,base=2)

array([1.00000000e+00, 5.65685425e+00, 3.20000000e+01, 1.81019336e+02,
       1.02400000e+03])